--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#000000"
foreground="#babdb6"
cursor="#ef2929"

-- Colors
color0="#2e3436"
color1="#cc0000"
color2="#4e9a06"
color3="#c4a000"
color4="#3465a4"
color5="#75507b"
color6="#06989a"
color7="#d3d7cf"
color8="#555753"
color9="#cc0000"
color10="#4e9a06"
color11="#c4a000"
color12="#3465a4"
color13="#75507b"
color14="#06989a"
color15="#d3d7cf"
